name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v14.9.0
        with:
          args: deploy --only hosting --project devtalk-planet
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
